### ISSUE TITLE
1.14 Support

### ISSUE THREAD

**Issue by SushiBarIV** [MrMaurice211/BungeeNPC#29]
# Make sure the info are filled before submitting your issue! Thank you!

### Check your server version
- [ ] Spigot 1.8.8
- [ ] Spigot 1.9.4
- [ ] Spigot 1.10.2
- [ ] Spigot 1.11.2
- [ ] Spigot 1.12.2
- [ ] Spigot 1.13.2
- [ ] PaperSpigot 1.8.8
- [ ] PaperSpigot 1.9.4
- [ ] PaperSpigot 1.10.2
- [ ] PaperSpigot 1.11.2
- [ ] PaperSpigot 1.12.2
- [ ] PaperSpigot 1.13.2
- [x] PaperSpigot 1.14.1

### Console show any error?
- [x] Yes
- [ ] No

Error [hastebin](https://hastebin.com/nilaseyibe.css)

### Description

When trying to start the Server, BungeeNPC won't enabled because its out of date.
I would love to see an Update in the Future... If you would still be on development.

**Comment by MrFreasy** [comment]
This plugin doesn't work with 1.14.
Isn't possible to update it or release the source code? 
Because I really need this plugin for my server...
This is the error that appears when you start the server: https://hastebin.com/elimidodal.css

**Comment by RoblokazPlays** [comment]
Same for me.
Please, **please** add 1.14 support! It's needed for new servers.

**Comment by MrMaurice211** [comment]
The plugin was last updated when 1.13 was recently released, so 1.14 will be supported on next update. Soon.
