### ISSUE TITLE
NPCs teleporting

### ISSUE THREAD

**Issue by RealMrRedNeck** [MrMaurice211/BungeeNPC#4]
# Make sure the info are filled before submitting your issue! Thank you!

### Check your server version
- [ ] Spigot 1.8.8
- [ ] Spigot 1.9.4
- [ ] Spigot 1.10.2
- [ ] Spigot 1.11.2
- [x] Spigot 1.12.2
- [ ] PaperSpigot 1.8.8
- [ ] PaperSpigot 1.9.4
- [ ] PaperSpigot 1.10.2
- [ ] PaperSpigot 1.11.2
- [ ] PaperSpigot 1.12.2

### Put here your plugin version, seen with  /bnpc plugin, if the command isnt available is because you dont have the latest version!

1.3.8

### Console show any error?
- [ ] Yes
- [X] No

If so, please paste a [hastebin](https://hastebin.com/) here

### Please describe when and how the error happen if possible!
It not a error but NPCs keep like teleporting to me

**Comment by Birsenberg** [comment]
Check your server version
 Spigot 1.12.2
Put here your plugin version, seen with /bnpc plugin, if the command isnt available is because you dont have the latest version!
1.3.8

Console show any error?
 No

It not a error but NPCs keep like teleporting to me

**Comment by RealMrRedNeck** [comment]
What? Birsenberg

**Comment by MrMaurice211** [comment]
It isnt a bug, its a feature for the NPC showing their skins, i will change the system in the next update!
